repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.12.0
    hooks:
      - id: pyupgrade
        args: ['--py311-plus']

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  # Configuration for black exists in pyproject.toml,
  # but we let pre-commit take care of the file filtering.
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ['-l 119']

  # Configuration for isort exists in pyproject.toml,
  # but we let pre-commit take care of the file filtering.
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: debug-statements

  - repo: local
    hooks:
      - id: no-auto-migrations
        name: no auto-named migrations
        entry: please provide a descriptive name for migrations
        language: fail
        files: .*/migrations/.*_auto_.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        entry: prettier --write --single-quote --trailing-comma=all
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |yaml|yml\
          )$"
