[tool.black]
# File filtering is taken care of in pre-commit.
line-length = 119
target-version = ['py311']

[tool.isort]
# File filtering is taken care of in pre-commit.
profile = "black"
lines_between_sections = 1
